name: getx_tube
description: A new Flutter project.


publish_to: 'none'

version: 1.0.0+1

environment:
  sdk: ">=2.12.0 <3.0.0"

dependencies:
  cached_network_image: ^3.1.0
  flutter:
    sdk: flutter
  flutter_localizations:
    sdk: flutter
  flutter_slidable: ^0.6.0
  get: ^4.3.8
  get_storage: ^2.0.3
  path_provider: ^2.0.5
  shared_preferences: ^2.0.7
  sizer: ^2.0.13
  timeago: ^3.1.0
  youtube_explode_dart: ^1.10.7-dev.1
  youtube_player_flutter: ^8.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter




flutter:
  uses-material-design: true

  
  generate: true

  assets:
    
    - assets/images/
